### ISSUE TITLE
The SDK does not support iOS 16. It crashes when I try to join

### ISSUE THREAD

**Issue by vladimirlineate** [bluejeans/ios-client-sdk#12]
Similar problem with another videostream project
https://github.com/BelledonneCommunications/linphone-sdk/issues/250

; "Linked against modern SDK, VOIP socket will not wake. Use Local Push Connectivity instead"
assembler comment in callstack

iOS 16 with XCode 14 no longer support VOIP socket

**Comment by InformamuseSRL** [comment]
Hi @pavankumarvvijapur and team

Any updates about this issue?
We cannot use the sdk on latest iOS release and it is very urgent issue.

**Comment by grihan6** [comment]
Ack'ed. 
My team is looking into this and would revert ASAP.

**Comment by grihan6** [comment]
BlueJeans would be fixing this issue in the next release planned for 31/Jan/23. Please stay tuned. Thanks for your patience.

**Comment by InformamuseSRL** [comment]
Hi @grihan6 
any news about new release scheduled for today?
Thanks

**Comment by chrisvoxy** [comment]
its feb 1, any updates? This is a pretty major issue that has been going on for months.

**Comment by grihan6** [comment]
Hi @chrisvoxy, @InformamuseSRL,
We encountered a blocker issue in last days of release testing and hence this release is running delayed.
Good news is that, we have fixed the issue and planning to release in couple of days.
Stay tuned.

**Comment by InformamuseSRL** [comment]
Hi @Gaurav

Do you plan to include flashlight and zoom control in the next release as requested here?
https://github.com/bluejeans/ios-client-sdk/issues/14 <https://github.com/bluejeans/ios-client-sdk/issues/14>


FP

 
Francesco Patronaggio | CTO
__________________________________________________________
 
InformAmuse S.r.l.  |  Spin-off accademico dell'Università degli Studi di Palermo
INDIRIZZO Via Terrasanta n. 39 — 90141 - Palermo ITALY. ***@***.***,13.3433553,17z/data=!3m1!4b1!4m5!3m4!1s0x1319ef456634827f:0x61a6c4610c8be748!8m2!3d38.1289299!4d13.345544> | TEL / FAX  +39 091 30 38 26 | TEL +39 091 781 72 71
 
 
Ai sensi del D.Lgs. 196/2003 si precisa che le informazioni contenute in questo messaggio sono riservate ed a uso esclusivo del destinatario. Qualora il messaggio in parola Le fosse pervenuto per errore, La invitiamo ad eliminarlo senza copiarlo e a non inoltrarlo a terzi, dandocene gentilmente comunicazione.Grazie.
Pursuant to Legislative Decree No. 196/2003, you are hereby informed that this message contains confidential information intended only for the use of the addressee. If you are not the addressee, and have received this message by mistake, please delete it and immediately notify us. You may not copy ordisseminate this message to anyone. 
 
 Rispetta l'ambiente. Non stampare questa mail se non è necessario.  Respect the environment. If it's not necessary, don't print this e-mail.

**Comment by GeorgeSealy** [comment]
Hi @chrisvoxy, @InformamuseSRL,

We've released the 1.7.0 version, which contains fixes to crashes occurring when using Xcode 14 and iOS 16. I'll close this issue out now, but let us know if you have any issues with the new release.
