### ISSUE TITLE
[AVCaptureVideoDataOutput setVideoSettings:] Video settings dimensions must maintain the source device activeFormat's aspect ratio

### ISSUE THREAD

**Issue by InformamuseSRL** [bluejeans/ios-client-sdk#13]
@ruairigriffin-bluejeans @pavankumarvvijapur 
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureVideoDataOutput setVideoSettings:] Video settings dimensions must maintain the source device activeFormat's aspect ratio'

**Comment by grihan6** [comment]
BlueJeans would be fixing this issue in the next release, planned on 31/Jan/23. Please stay tuned. Thanks for your patience.

**Comment by InformamuseSRL** [comment]
Hi @grihan6 
any news about new release scheduled for today?
Thanks

**Comment by grihan6** [comment]
Hi @InformamuseSRL ,
We are still working on fixing this issue. 
This was expected to be fixed with current upcoming release (planned in couple of days, which is v1.7.0) but due to it's complicated nature, we are planning to patch it (or release it) soon after this release.
Stay tuned.

**Comment by InformamuseSRL** [comment]
Hi @grihan6 

Do you plan to include also flashlight and zoom control in the next release as requested here?
https://github.com/bluejeans/ios-client-sdk/issues/14

**Comment by GeorgeSealy** [comment]
Hi @InformamuseSRL - the 1.7.0 release is out now and should fix this exception. Please try the update and let us know if you have any further issues.
