### ISSUE TITLE
Dependencies and dependency management

### ISSUE THREAD

**Issue by powerje** [bluejeans/ios-client-sdk#2]
There are a number of dependencies in the SDK that I would prefer not to incorporate into my app and some that conflict with other packages requirements.

Are there any plans to remove dependencies like CocoaLumberjack & Mixpanel? In my opinion, things like logging and analytics should be handled by the client application. A logging interface the client could implement would be nice though!

One thing that might ease the pain of integrating the SDK would be to publish the SDK via [Swift Package Manager](https://swift.org/package-manager/), which may find versions of SDKs required by BlueJeans and other packages that are compatible with both. That said, it would still be ideal if BlueJeans did not force including logging/analytics frameworks.

**Comment by GeorgeSealy** [comment]
We are planning to add SPM support in an upcoming release. As for the dependencies on Mixpanel and CocoaLumberjack, it's something we are looking into, but too early to give a definite answer on. As soon as I have a more definite answer I'll update here.

**Comment by GeorgeSealy** [comment]
Closing this issue out for now, as this kind of update to our dependency management is not on the immediate roadmap. We are looking for potential improvements that can be made here and will aim to improve this in the future.
